#!/usr/bin/env python3
"""Review Gradle SHA-256 candidates against the audit and primary Maven publishers.
Run only when intentionally preparing verification metadata, never during a build.
No Gradle/plugin code is executed; failures do not modify the allowlist.
"""
import concurrent.futures
import hashlib
import json
from pathlib import Path
import re
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET

root=Path(__file__).resolve().parents[1]
ns={'v':'https://schema.gradle.org/dependency-verification'}
path=root/'gradle/verification-metadata.xml'
tree=ET.parse(path)
historical={}
for p in (root/'security-audit-evidence').glob('*artifact-published-sha256.json'):
    for r in json.loads(p.read_text())['results']:
        if r['status']=='match':
            historical[(r['coordinate'],r['artifact'])]=r['official_sha256']
previous={}
report_path=root/'security-remediation-evidence/dependency-publisher-verification.json'
if report_path.exists():
    previous={(r['coordinate'],r['artifact'],r['sha256']):r for r in json.loads(report_path.read_text())['results'] if r['status']=='match'}
items=[]
for component in tree.findall('.//v:component',ns):
    g,n,v=(component.get(x) for x in ('group','name','version'))
    for artifact in component.findall('v:artifact',ns):
        hashes=[x.get('value') for x in artifact.findall('v:sha256',ns)]
        if len(hashes)!=1:raise SystemExit('Expected one SHA-256 per immutable artifact')
        items.append((g,n,v,artifact.get('name'),hashes[0]))
def fetch(url):
    with urllib.request.urlopen(url,timeout=40) as r:
        if not r.url.startswith('https://'):raise ValueError('insecure publisher redirect')
        h=hashlib.sha256()
        while block:=r.read(1024*1024):h.update(block)
        return h.hexdigest()
def verify(item):
    g,n,v,a,digest=item;coordinate=f'{g}:{n}:{v}'
    if (coordinate,a,digest) in previous:return previous[(coordinate,a,digest)]
    expected=historical.get((coordinate,a));method='historical audited publisher hash';url=None
    try:
        if expected is None:
            google=g=='com.android' or g.startswith(('androidx.','com.android.','com.google.testing.platform'))
            base='https://dl.google.com/dl/android/maven2/' if google else 'https://repo.maven.apache.org/maven2/'
            url=base+g.replace('.','/')+'/'+n+'/'+v+'/'+a
            try:
                with urllib.request.urlopen(url+'.sha256',timeout=25) as response:
                    text=response.read(1024).decode('ascii').strip().split()[0]
                    if not re.fullmatch('[a-fA-F0-9]{64}',text):raise ValueError('invalid sidecar')
                    expected=text.lower();method='publisher SHA-256 sidecar'
            except (urllib.error.HTTPError,ValueError):
                try:
                    module_url=base+g.replace('.','/')+'/'+n+'/'+v+'/'+n+'-'+v+'.module'
                    with urllib.request.urlopen(module_url,timeout=25) as response:module=json.load(response)
                    found=[f for variant in module['variants'] for f in variant.get('files',[]) if f.get('name')==a and re.fullmatch('[a-f0-9]{64}',f.get('sha256',''))]
                    if not found:raise ValueError('no module checksum')
                    expected=found[0]['sha256'];method='official Gradle module SHA-256';url=module_url
                except (urllib.error.HTTPError,KeyError,ValueError):
                    expected=fetch(url);method='independent primary-publisher download'
        return dict(coordinate=coordinate,artifact=a,sha256=digest,publisher_sha256=expected,method=method,url=url,status='match' if digest==expected else 'MISMATCH')
    except Exception as e:return dict(coordinate=coordinate,artifact=a,sha256=digest,status='ERROR',error=type(e).__name__,url=url)
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:results=list(pool.map(verify,items))
report={'artifacts':len(results),'matches':sum(r['status']=='match' for r in results),'historical':sum(r.get('method')=='historical audited publisher hash' for r in results),'results':results}
(root/'security-remediation-evidence/dependency-publisher-verification.json').write_text(json.dumps(report,indent=2)+'\n')
print({k:v for k,v in report.items() if k!='results'})
for r in results:
    if r['status']!='match':print(r)
if report['matches']!=report['artifacts']:raise SystemExit(1)
# Preserve Gradle's formatting. This is explanatory provenance, not a trust wildcard.
path.write_text(path.read_text().replace('origin="Generated by Gradle"','origin="Reviewed: audit/publisher hashes; see dependency-publisher-verification.json"'))
